### ISSUE TITLE
Only owners should be able to have access to pages

### ISSUE THREAD

**Issue by vincekyi** [UCLA-BD2K/BioComposer#58]
a user who does not have access will be denied
a user who does have access can edit the page

**Comment by defibull** [comment]
{
 owner: if true
}

**Comment by defibull** [comment]
Modifying the getfiles function so that we can limit display of files based on owners

**Comment by defibull** [comment]
Changing the wikifile schema to just have user id rather than the user object itself (I am assuming that userids are unique)
