### ISSUE TITLE
Create endpoint to allow users to save citation

### ISSUE THREAD

**Issue by vincekyi** [UCLA-BD2K/BioComposer#61]
Should be a REST post request to add a citation to the saved list

**Comment by defibull** [comment]
Created function properties in the model to allow users to save citations

**Comment by defibull** [comment]
Analyzing past code, to figure out how citations are internally formatted before insertion i.e. what series of functions are called to generate citation objects and then store them in the document that is stored in the database

**Comment by defibull** [comment]
Since all file citations are in a singleton, attempting to decouple user enacted citations from file citations/pre-existing citations
