### ISSUE TITLE
User login password reset shows error page

### ISSUE THREAD

**Issue by jli3** [UCLA-BD2K/BioComposer#73]
When user clicks "Forgot Password?", enters their email address, and presses "Reset", an error page appears and no email is sent.

**Comment by defibull** [comment]
@AustinNassoUCLA : this error appears in the release version too, in that version I changed the mongodb from local host to mlab - do you that has to do with the error? (That was the only change in the database)

**Comment by defibull** [comment]
Figured out the problem: the path to save was written as localhost - changing that to a relative path in order to solve the issue
