### ISSUE TITLE
Implement the content-acquisition panel

### ISSUE THREAD

**Issue by vincekyi** [UCLA-BD2K/BioComposer#8]
Using the Pubmed and Google Scholar API, implement the panel for searching papers relevant to keywords and obtaining abstracts of a particular paper.

**Comment by AustinNassoUCLA** [comment]
I implemented the tabs and made it resizable via javascript

**Comment by AustinNassoUCLA** [comment]
BASIC search for Pubmed articles exists... It gives the basic idea of how this will work. Searches their database without page reload.

Features I still need to implement:
- Get abstract info
- Re-create entire thing with Google API
- Favorites
- Generate citations
